# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Farewell Way!
tagline:          'A personal blog'
description:      'This is a personal webpage designed to link content created on other platforms and organize thoughts and research on technical topics. The webpage is intended to reflect a personal way of learning and understanding things, with the aim of creating a comprehensive resource for both the owner and visitors to the site.'
url:              https://albertost85.github.io
homepage:         https://www.farewellway.com/
baseurl:          /

author:
  name:           'Alberto Simon'
  url:            https://linkedin.com/albertosimon

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/albertost85/albertost85.github.io
